export const lifeboatDetails: { [key: string]: string } = {
	"1": "General view of the lifeboat(s) from all sides",
	"2": "Markings: number of persons, number of the lifeboat, name and port of registry of the ship (LSA 4.4.9)",
	"3": "General view inside from aft",
	"4": "General view inside from fwd",
	"5": "Approval plate, endorsed by the Administration or its representative",
	"6": "Seating position clearly indicated in the lifeboat",
	"7": "Boarding ladder",
	"8": "Starter batteries with gas venting (LSA 4.4.6.9)",
	"9": "Drain valves with a cap or plug",
	"10": "Rudder and tiller",
	"11": "Handholds or a buoyant lifeline (LSA 4.4.7.3)",
	"12": "Equipment (LSA 4.4.8):",
	"12.1": "buoyant oars, thole pins, crutches",
	"12.2": "two boat-hooks",
	"12.3": "buoyant bailer and two buckets",
	"12.4": "survival manual",
	"12.5": "lighted compass",
	"12.6": "magnetic compass readings",
	"12.7": "sea-anchor",
	"12.8": "two efficient painters",
	"12.9": "two hatchets",
	"12.10": "watertight receptacles with fresh water",
	"12.11": "rustproof dipper with lanyard",
	"12.12": "rustproof graduated drinking vessel",
	"12.13": "food ration general",
	"12.14": "food ration expiry date",
	"12.15": "four rocket parachute flares general",
	"12.16": "four rocket parachute flares expiry date",
	"12.17": "six hand flares general",
	"12.18": "six hand flares expiry date",
	"12.19": "two buoyant smoke signals general",
	"12.20": "two buoyant smoke signals expiry date",
	"12.21": "working waterproof electric torch and one spare bulb",
	"12.22": "daylight signaling mirror with instructions",
	"12.23": "copy of the life-saving signals",
	"12.24": "whistle or equivalent sound signal",
	"12.25": "first-aid outfit expiry date",
	"12.26": "anti-seasickness medicine general",
	"12.27": "anti-seasickness medicine expiry date",
	"12.28": "jack-knife",
	"12.29": "tin openers",
	"12.30": "rescue quoits with line",
	"12.31": "manual pump",
	"12.32": "fishing tackle",
	"12.33": "tools for minor adjustments to the engine",
	"12.34": "portable fire-extinguishing equipment",
	"12.35": "searchlight",
	"12.36": "radar reflector or radar transponder",
	"12.37": "thermal protective aids",
};

export const rescueBoatDetails: { [key: string]: string } = {
	"1": "General view of the rescue boat from all sides",
	"2": "Equipment (LSA 5.1.2.2):",
	"2.1": "buoyant oars or paddles, thole pins, crutches",
	"2.2": "buoyant bailer",
	"2.3": "binnacle with lighted compass",
	"2.4": "sea-anchor",
	"2.5": "painter",
	"2.6": "buoyant line",
	"2.7":
		"waterproof electric torch with one spare set of batteries and one spare bulb",
	"2.8": "whistle or equivalent sound signal",
	"2.9": "first-aid outfit with expiry date",
	"2.10": "rescue quoits",
	"2.11": "searchlight",
	"2.12": "radar reflector",
	"2.13": "thermal protective aids",
	"2.14": "portable fire-extinguishing equipment",
	"2.15": "boat hook (rigid rescue boat)",
	"2.16": "bucket (rigid rescue boat)",
	"2.17": "knife or hatchet (rigid rescue boat)",
	"2.18": "buoyant safety knife (inflated rescue boat)",
	"2.19": "sponges (inflated rescue boat)",
	"2.20": "manually operated bellows or pump (inflated rescue boat)",
	"2.21": "repair kit (inflated rescue boat)",
	"2.22": "safety boat-hook (inflated rescue boat)",
	"2.23":
		"VHF radiocommunication set which is hands-free and watertight (fast rescue boat)",
};

export const requiredCopies: { [key: string]: string } = {
	"1": "Certificate or declaration of conformity lifeboat (LSA 4.4.1.2)",
	"2": "Certificate or declaration of conformity rescue boat (LSA 4.4.1.2)",
	"3": "Muster list",
	"4": "Last lifeboat drill report",
	"5": "Lifeboat and rescue boat maintenance procedures, including (SOLAS III reg 36):",
	"5.1": "checklist for use when carrying out the inspections",
	"5.2": "maintenance and repair instructions",
	"5.3": "schedule of periodic maintenance",
	"5.4": "diagram of lubrication points with the recommended lubricants",
	"5.5": "list of replaceable parts",
	"5.6": "list of sources of spare parts; and",
	"5.7": "log for records of inspections and maintenance",
};

export const requiredVideos: { [key: string]: string } = {
	"1": "Propeller - ahead and astern propulsion (LSA 4.4.6.5)",
	"2": "Rescue boat engine working",
};
